input {
  kafka {
    bootstrap_servers => "kafka:29092"
    topics => ["kitsune_metrics"]
    group_id => "logstash-kitsune-metrics"
    auto_offset_reset => "latest"
    codec => json
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "kitsune_metrics-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
