input {
  kafka {
    bootstrap_servers => "kafka:29092"
    topics => ["kitsune_enriched"]
    group_id => "logstash-kitsune"
    auto_offset_reset => "latest"
    codec => json
  }
}

filter {
  # ne pas écraser @timestamp
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "kitsune_enriched-%{+YYYY.MM.dd}"
    document_id => "%{partition}-%{offset}"
  }
}


